services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecommerce_template
      POSTGRES_PASSWORD: ecommerce_template_dev_password
      POSTGRES_DB: ecommerce_template
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
